// This file is automatically generated and contains assets from gnosis.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssetAggregators: Address[][];
}

export const WXDAI_ADDRESS = Address.fromString('0xe91d153e0b41518a2ce8dd3d7944fa863463a97d');
export const USDC_ADDRESS = Address.fromString('0xddafbb505ad214d7b80b1f830fccc89b60fb7a83');
export const USDT_ADDRESS = Address.fromString('0x4ecaba5870353805a9f068101a40e0f32ed605c6');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0xe91d153e0b41518a2ce8dd3d7944fa863463a97d'), // WXDAI
    Address.fromString('0xddafbb505ad214d7b80b1f830fccc89b60fb7a83'), // USDC
    Address.fromString('0x4ecaba5870353805a9f068101a40e0f32ed605c6'), // USDT
  ],
  pricingAssets: [
    Address.fromString('0x6a023ccd1ff6f2045c3309768ead9e68f978f6e1'), // WETH
    Address.fromString('0x8e5bBbb09Ed1ebdE8674Cda39A0c169401db4252'), // WBTC
    Address.fromString('0x9c58bacc331c9aa871afd802db6379a98e80cedb'), // GNO
    Address.fromString('0xd4015683b8153666190e0b2bec352580ebc4caca'), // bb-ag-WBTC
    Address.fromString('0xbb9cd48d33033f5effbedec9dd700c7d7e1dcf50'), // bb-ag-WETH
    Address.fromString('0xfedb19ec000d38d92af4b21436870f115db22725'), // bb-ag-USD
    Address.fromString('0x41211bba6d37f5a74b22e667533f080c7c7f3f13'), // bb-ag-WXDAI
    Address.fromString('0xd16f72b02da5f51231fde542a8b9e2777a478c88'), // bb-ag-USDT
    Address.fromString('0xe7f88d7d4ef2eb18fcf9dd7216ba7da1c46f3dd6'), // bb-ag-USDC
    Address.fromString('0xffff76a3280e95dc855696111c2562da09db2ac0'), // bb-ag-GNO
  ],
  fxAssetAggregators: [
  ],
};
