name: CI

on:
  push:
    branches: master
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      #- name: Lint
        #run: yarn lint
  abi-integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }} # `PAT` stored in secrets that has access to the core contracts repo
          submodules: true
      - name: check abis
        run: diff -rq abis core/abi
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }} # `PAT` stored in secrets that has access to the core contracts repo
          submodules: true
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn --frozen-lockfile
      - name: start up docker services
        run: yarn start:parity -d
      - name: install core packagase
        run: cd core && yarn
      - name: deploy contracts
        run: cd core && yarn redeploy:docker
      - name: codegen
        run: yarn codegen
      - name: deploy subgraph
        run: yarn create:local && yarn deploy:local
      - name: test
        run: yarn test
env:
  CI: true
